### ISSUE TITLE
Angular 14

### ISSUE THREAD

**Issue by ghost** [nigrosimone/ng-for-track-by-property#1]
Hi. Thank you for this library. This is something that Angular should support natively.

Could you please update the Angular Version to 14.

**Comment by nigrosimone** [comment]
Hi @SergejSintschilin I have upgraded to Angular 14!

Thanks for using my library and take a look to my other Angular libraries https://www.npmjs.com/~nigro.simone

**Comment by ghost** [comment]
Oh. Thanks. This was fast.

**Comment by ghost** [comment]
You forgot to change it here.
😄 
https://github.com/nigrosimone/ng-for-track-by-property/blob/main/projects/ng-for-track-by-property/package.json

**Comment by nigrosimone** [comment]
ops! fixed
